Repository Team-Beta-GraceShopper/GraceShopper, pull requests merged in 2021-01, with the labels that each got.

#2 feat(product model): added product db schema
  server/db/models/products.js
Labels: enhancement

#12 Feat(user db)
  package.json
  script/seed.js
  server/db/models/user.js
Labels: enhancement

#7 feat(order and orderdetails models): Added order and order detail mod…
  package.json
  script/seed.js
  server/db/models/index.js
  server/db/models/orderDetails.js
  server/db/models/orders.js
Labels: enhancement

#11 Feat (Added cart model and dummy data)
  package.json
  script/seed.js
  server/db/models/cart.js
  server/db/models/index.js
Labels: enhancement

#10 NewFeat(product model): added dummy data to product model
  script/seed.js
  server/db/models/product.js
Labels: enhancement

#14 bug(seed data): Fixed and merged all separate seed data and models
  script/seed.js
  server/db/models/cart.js
  server/db/models/index.js
Labels: bug

#15 feat(order and order details models): added order and order detail mo…
  script/seed.js
Labels: enhancement

#16 New order models
  server/db/models/index.js
  server/db/models/orderDetails.js
  server/db/models/orders.js
Labels: enhancement

#17 feat(allCategoriescComp): added all categories component to homepage
  client/app.js
  client/components/all-catergories.js
Labels: enhancement

#18 feat(product routes): created backend routes
  client/components/sweaters.js
  server/api/index.js
  server/api/products.js
Labels: enhancement

#20 feat(redux): added categories model to database, added products redux…
  client/app.js
  client/components/all-categories.js
  client/components/all-catergories.js
  client/components/home.js
  client/components/index.js
  client/components/notFound.js
  client/routes.js
  client/store/index.js
  client/store/products.js
  public/index.html
  script/seed.js
  server/db/models/categories.js
  server/db/models/index.js
  server/db/models/product.js
Labels: enhancement

#22 feat(cartComponent): added portion of redux
  client/store/products.js
Labels: enhancement

#25 feat(modified redux store): updated products state to incorporate cha…
  client/components/all-products.js
  client/components/index.js
  client/components/single-product.js
  client/routes.js
  client/store/products.js
  server/db/models/index.js
  server/db/models/orderDetails.js
  server/db/models/orders.js
Labels: enhancement

#26 feat(cart component w/ routes): added routes and cart comp
  client/components/cart.js
  client/components/index.js
  client/routes.js
  client/store/products.js
  script/seed.js
  server/api/index.js
  server/api/orderDetails.js
  server/db/models/index.js
  server/db/models/orderDetails.js
Labels: enhancement

#30 feat(single-product):added cart redux store
  client/components/single-product.js
  client/store/cart.js
  client/store/index.js
  client/store/products.js
Labels: enhancement

#31 Feat(cartFrontEnd): add portions of cart front end
  client/components/cart.js
  client/routes.js
Labels: enhancement

#33 Feat updated cart redux
  client/components/cart.js
  client/components/navbar.js
  client/components/single-product.js
  client/routes.js
  client/store/cart.js
  script/seed.js
  server/api/orderDetails.js
  server/db/models/orderDetails.js
Labels: enhancement

#34 Deploy heroku
  public/bundle.js
  public/bundle.js.map
  server/db/db.js
Labels: enhancement

#37 Persistence & Checkout
  client/components/all-products.js
  client/components/cart.js
  client/components/checkout.js
  client/components/navbar.js
  client/components/single-product.js
  client/routes.js
  client/store/cart.js
  client/store/index.js
  client/store/orders.js
  public/bundle.js
  public/bundle.js.map
  public/style.css
  server/api/index.js
  server/api/orders.js
  server/db/models/orderDetails.js
Labels: enhancement

#43 Updated checkout
  client/components/cart.js
  client/components/checkout.js
  client/components/checkoutDetails.js
  client/components/index.js
  client/components/single-product.js
  client/routes.js
  client/store/cart.js
  client/store/orders.js
  public/bundle.js
  public/bundle.js.map
  public/style.css
  script/seed.js
  server/api/orderDetails.js
  server/api/orders.js
  server/db/models/index.js
  server/db/models/orderDetails.js
  server/db/models/orders.js
Labels: enhancement

#44 Feat(admin auth data validate)
  client/components/checkout.js
  client/components/user-home.js
  public/bundle.js
  public/bundle.js.map
  server/api/orderDetails.js
  server/api/orders.js
  server/api/products.js
  server/api/users.js
Labels: enhancement

#53 Update to master
  client/components/checkout.js
Labels: enhancement

#54 feat(updated seed file): added products and users to seed file; also …
  client/components/all-products.js
  client/components/cart.js
  client/components/single-product.js
  public/style.css
  script/seed.js
  server/api/orderDetails.js
  server/api/orders.js
  server/db/models/product.js
Labels: enhancement

#55 Feat user admin security
  server/api/orderDetails.js
  server/api/orders.js
  server/api/products.js
  server/api/users.js
Labels: enhancement

#56 final commit with clean version
  client/components/all-products.js
  client/components/cart.js
  client/components/checkout.js
  client/components/checkoutDetails.js
  client/components/navbar.js
  client/components/notFound.js
  client/components/single-product.js
  client/components/user-home.js
  client/routes.js
  client/store/cart.js
  client/store/index.js
  client/store/user.js
  server/api/orderDetails.js
  server/api/orders.js
  server/api/users.js
  server/db/models/orderDetails.js
  server/db/models/orders.js
Labels: documentation

#57 final-touches
  script/seed.js
  server/api/products.js
Labels: enhancement

#58 changed security routes
  server/api/products.js
Labels: enhancement
